# Common configuration for Breadcrumb guidance system


# System Settings
system:
  #How fast for the control loop to operate at
  nav_rate: 25.0
  #Timeout for the contact with the mav in seconds
  state_timeout: 5.0
  ext_timeout: 2.0
  #Frame of reference to output velocity goals
  vel_frame: "body"

# TF Settings
tf:
  #Frame that the UAV and goal exist in
  world_frame: "world"
  #Name of the UAV frame
  body_frame: "fcu"
  #The name that the goal frame will be given
  goal_frame: "breadcrumb_goal"

# Flight Presets
guidance:
  #Home should be in the air, most likely above landing
  home_x: 0.0
  home_y: 0.0
  home_z: 1.0
  home_h: 0.0
  #Takeoff Height will be were the UAV rises to on takeoff
  takeoff_height: 1.0
  #Radius of the waypoint for it to be reached
  wp_radius: 0.1
  #Accuracy of the heading for the waypoint to be reached (in radians)
  hdg_acc: 0.1

# Horizontal Position Controller
pos_xy_pid:
  p: 0.4
  i: 0.0
  d: 0.05
  min: -0.1
  max: 0.1

# Vertical Position Controller
pos_z_pid:
  p: 1.0
  i: 0.0
  d: 0.0
  min: -0.5
  max: 1.0

# Heading Rate Controller
h_pid:
  p: 0.5
  i: 0.0
  d: 0.05
  min: -0.8 #radians per second
  max: 0.8  #radians per second


#	P		I		D		Max		Output
#	0.4		0.0		0.0		10.0	//XY Position
#	1.0		0.0		0.0		10.0	//Z Position

#	0.2		0.2		0.005	0.5		//XY Vel
#	0.4		0.0		2.0		1.0		//Z Vel

